In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
dataset=pd.read_csv('/content/sample_data/Iris.csv')
dataset

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [8]:
from pandas.core.common import standardize_mapping
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(dataset.drop('Species',axis=1))

StandardScaler()

In [9]:
a=scalar.transform(dataset.drop('Species',axis=1))
new_data=pd.DataFrame(a,columns=dataset.columns[:-1])
new_data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   -1.720542      -0.900681      1.032057      -1.341272     -1.312977
1   -1.697448      -1.143017     -0.124958      -1.341272     -1.312977
2   -1.674353      -1.385353      0.337848      -1.398138     -1.312977
3   -1.651258      -1.506521      0.106445      -1.284407     -1.312977
4   -1.628164      -1.021849      1.263460      -1.341272     -1.312977
..        ...            ...           ...            ...           ...
145  1.628164       1.038005     -0.124958       0.819624      1.447956
146  1.651258       0.553333     -1.281972       0.705893      0.922064
147  1.674353       0.795669     -0.124958       0.819624      1.053537
148  1.697448       0.432165      0.800654       0.933356      1.447956
149  1.720542       0.068662     -0.124958       0.762759      0.790591

[150 rows x 5 columns]

In [11]:
from sklearn.model_selection  import train_test_split
x=new_data#=dt.Class
y=dataset['Species']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size= 0.3,random_state=90)

In [12]:
from sklearn.naive_bayes import GaussianNB,BernoulliNB,CategoricalNB
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.metrics import accuracy_score

In [14]:
scores=[]
classifier=GaussianNB()
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
scores.append(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(scores)

[[16  0  0]
 [ 0  9  0]
 [ 0  0 20]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        20

       accuracy                           1.00        45
      macro avg       1.00      1.00      1.00        45
   weighted avg       1.00      1.00      1.00        45

[1.0]
