**PROGRAM NO-2**

**Aim**: Matrix operations (using vectorization) and transformation using python and SVD using Python.


In [2]:
import numpy as np

In [3]:
a=np.zeros(10)

In [4]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
b=np.ones(10)

In [6]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
b*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
c=np.arange(10,51)

In [9]:
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [10]:
d=np.arange(2,51,2)

In [11]:
d

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [12]:
e=np.arange(10,51,2)

In [13]:
e

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
a=[[0,1,2],[3,4,5],[6,7,8]]

In [14]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
b=np.array(a)

In [16]:
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
np.random.randint(0,1)

0

In [20]:
np.random.randint(0,1)

0

In [21]:
q=np.arange(0,9)

In [22]:
q

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
q.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
np.random.rand(0,1)

array([], shape=(0, 1), dtype=float64)

In [26]:
np.random.rand(1)

array([0.26923218])

In [27]:
np.random.randint(1,100,25)

array([ 1, 44, 60, 90,  6, 91, 10, 33, 36, 25, 86, 59, 62,  4, 41, 88, 22,
       59, 16, 43, 46, 77, 17, 43, 40])

In [28]:
np.random.randint(0,1,25)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [29]:
np.random.rand(25)

array([0.02604834, 0.43697673, 0.61063743, 0.5521478 , 0.35100812,
       0.84180282, 0.95023874, 0.59802574, 0.78318149, 0.53882999,
       0.74947205, 0.72755624, 0.41153834, 0.17001939, 0.82088417,
       0.45508234, 0.9391521 , 0.55629557, 0.20195689, 0.22017767,
       0.71916734, 0.2831506 , 0.19306512, 0.4536317 , 0.57645679])

In [30]:
np.random.randint(25)

19

In [31]:
np.random.randn(25)

array([-1.77428577, -0.34755799,  1.5404791 , -0.33227642,  0.99302388,
        1.17065137, -0.50864006, -2.20377038,  0.89444993, -0.02526389,
       -0.05315099,  0.07083702, -1.58277371,  1.34586638,  0.18431246,
       -0.25268493,  1.38844065,  0.67843225, -0.49752421,  0.31943281,
       -0.04236431,  0.08995847,  0.55687512,  2.1232632 , -0.33435369])

In [32]:
np.random.randn(5,5)

array([[ 1.86492465, -0.15014286, -0.09765767, -1.31443206,  0.47820978],
       [ 1.15904514, -0.35821814, -0.35333316, -1.51616695,  0.22008186],
       [-0.50349877, -1.14953684,  1.554723  , -0.95321233,  0.03748347],
       [ 0.33126718,  1.12498118,  0.13902522,  0.53102246,  0.70039766],
       [-0.46427642, -2.09666164, -2.30556989, -1.14550368,  2.60364851]])

In [33]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [34]:
np.arange(0,1,0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [35]:
np.arange(0.01,1.01,0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [36]:
a=np.arange(0.01,1.01,0.01)

In [37]:
a.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [38]:
p=np.arange(0,101,1)

In [39]:
p

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [40]:
p=np.arange(1,101,1)

In [41]:
p/10

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
        4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
        5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
        6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,
        7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,
        8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9,
       10. ])

In [42]:
p/100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [43]:
p=p.reshape(10,10)

In [44]:
p

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [45]:
p/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [46]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [47]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [48]:
g=np.arange(1,26)

In [50]:
g=g.reshape(5,5)

In [51]:
g

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
g[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [53]:
g[3:,5:]

array([], shape=(2, 0), dtype=int64)

In [54]:
g

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [55]:
g[3:,4:]

array([[20],
       [25]])

In [56]:
g[3:3,4:4]

array([], shape=(0, 0), dtype=int64)

In [57]:
g[3:4,4:]

array([[20]])

In [58]:
g[3,4]

20

In [59]:
g[1:1,:2]

array([], shape=(0, 2), dtype=int64)

In [60]:
g[1:,0:2]

array([[ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22]])

In [62]:
g[0:3,1:1]

array([], shape=(3, 0), dtype=int64)

In [63]:
g[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [64]:
g[:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [65]:
g[4:,0:]

array([[21, 22, 23, 24, 25]])

In [66]:
g[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [68]:
g.sum()

325

In [71]:
g.std()

7.211102550927978

In [72]:
import numpy as np
A = np.arange(0,25)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [73]:
#SVD

from scipy.linalg import svd
a = np.arange(1,19).reshape(6,3)
U, s, VT = svd(a)
U

array([[-0.07736219,  0.71960032, -0.09075777, -0.25083666, -0.45979172,
        -0.4400296 ],
       [-0.19033085,  0.50893247,  0.58409372,  0.4022013 ,  0.06897105,
         0.44392965],
       [-0.3032995 ,  0.29826463, -0.34118019, -0.54123699,  0.50890998,
         0.38822268],
       [-0.41626816,  0.08759679, -0.61888418,  0.65636038,  0.03282454,
        -0.06437079],
       [-0.52923682, -0.12307105,  0.37872289, -0.04363171,  0.43069535,
        -0.61149707],
       [-0.64220548, -0.33373889,  0.08800553, -0.22285632, -0.58160921,
         0.28374512]])

In [74]:
s

array([4.58945322e+01, 1.64070530e+00, 1.74146424e-15])

In [75]:
VT

array([[-0.52903535, -0.57607152, -0.62310769],
       [-0.74394551, -0.03840487,  0.66713577],
       [ 0.40824829, -0.81649658,  0.40824829]])

In [76]:
U, s, VT = svd(a,full_matrices=True)

In [77]:
U

array([[-0.07736219,  0.71960032, -0.09075777, -0.25083666, -0.45979172,
        -0.4400296 ],
       [-0.19033085,  0.50893247,  0.58409372,  0.4022013 ,  0.06897105,
         0.44392965],
       [-0.3032995 ,  0.29826463, -0.34118019, -0.54123699,  0.50890998,
         0.38822268],
       [-0.41626816,  0.08759679, -0.61888418,  0.65636038,  0.03282454,
        -0.06437079],
       [-0.52923682, -0.12307105,  0.37872289, -0.04363171,  0.43069535,
        -0.61149707],
       [-0.64220548, -0.33373889,  0.08800553, -0.22285632, -0.58160921,
         0.28374512]])

In [78]:
U, s, VT = svd(a,full_matrices=False)
U

array([[-0.07736219,  0.71960032, -0.09075777],
       [-0.19033085,  0.50893247,  0.58409372],
       [-0.3032995 ,  0.29826463, -0.34118019],
       [-0.41626816,  0.08759679, -0.61888418],
       [-0.52923682, -0.12307105,  0.37872289],
       [-0.64220548, -0.33373889,  0.08800553]])

In [79]:
from numpy import diag
from numpy import dot
a= (U @ np.diag(s) @ VT)
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])

Result: The program is executed successfully and obtained the output.